sudo: false
dist: trusty
language: node_js

cache:
  directories:
    - node_modules

addons:
  chrome: stable

node_js:
  - "8"

matrix:
  fast_finish: true

before_install:
  - npm install npm@5 -g
  - npm cache verify
  - npm prune
  - npm update
  - npm install -g @angular/cli
  - npm install -g firebase-tools

install:
  - npm install


script:
  - ng build --prod --build-optimizer
  - firebase deploy --only hosting --token "$FIREBASE_TOKEN"