# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.11.1

pipelines:
  default:
    - step:
        name: 'Install dependencies'
        caches:
          - node
        script:
          - npm install -g @angular/cli
          - npm install
    - step:
        name: 'Build'
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - ng build --prod --build-optimizer
          
    - step:
        name: 'Deploy'
        deployment: 'production'
        caches:
          - node
        script:
          - firebase deploy --only hosting --token "$FIREBASE_TOKEN"