steps:
  - name: node:10.15.1
    entrypoint: npm
    args: ['install']

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'install' ]

  # Build productive files
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run', 'build', '--prod' ]

  # Deploy
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy']
